---
version: "3"

services:
  grafana:
    image: "grafana/grafana:10.0.1"
    volumes:
      - "./conf/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_FEATURE_TOGGLES_ENABLE=traceqlEditor"
    ports:
      - "127.0.0.1:3000:3000"
  prometheus:
    image: "prom/prometheus:v2.45.0"
    command:
      - "--config.file=/etc/prometheus.yaml"
      - "--enable-feature=exemplar-storage"
      - "--web.enable-remote-write-receiver"
    volumes:
      - "./conf/prometheus.yaml:/etc/prometheus.yaml"
    ports:
      - "127.0.0.1:9090:9090"
  tempo:
    image: "grafana/tempo:2.1.1"
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - "./conf/tempo.yaml:/etc/tempo.yaml"
    ports:
      - "127.0.0.1:3200:3200"    # Tempo
      - "127.0.0.1:4317:4317"    # OTLP GRPC
      - "127.0.0.1:14268:14268"  # Jaeger
  traefik:
    image: "traefik:v2.10.3"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # tracing
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.collector.endpoint=http://tempo:14268/api/traces?format=jaeger.thrift"
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  uservice1:
    build: uservice1
    ports:
      - "127.0.0.1:8081:7878"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uservice1.rule=Host(`uservice1.localhost`)"
      - "traefik.http.routers.uservice1.entrypoints=web"
  uservice2:
    build: uservice2
    ports:
      - "127.0.0.1:8082:7878"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uservice2.rule=Host(`uservice2.localhost`)"
      - "traefik.http.routers.uservice2.entrypoints=web"
  uservice3:
    build: uservice3
    ports:
      - "127.0.0.1:8083:7878"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uservice3.rule=Host(`uservice3.localhost`)"
      - "traefik.http.routers.uservice3.entrypoints=web"
    environment:
      # set OTLP collector address
      # https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/#otel_exporter_otlp_traces_endpoint
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo:4317
  uservice4:
    build: uservice4
    ports:
      - "127.0.0.1:8084:7878"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uservice4.rule=Host(`uservice4.localhost`)"
      - "traefik.http.routers.uservice4.entrypoints=web"
    environment:
      # set OTLP collector address
      # https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/#otel_exporter_otlp_traces_endpoint
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo:4317
